### ISSUE TITLE
Deprecated network annotation in Ingress definition

### ISSUE THREAD

**Issue by JannesLathouwers** [EOEPCA/rm-workspace-api#13]
When deploying the Helm chart to a k8s cluster that is running a k8s version higher than 1.21.5 I encounter the following error:
```
helm install --values values.yaml workspace-api eoepca/rm-workspace-api
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Ingress" in version "networking.k8s.io/v1beta1"
```
This is due to the use of deprecated Ingress annotations (also has been encountered in other building blocks).
The chart from `helm-charts-dev` has the same issue as far as I can tell.

Kind regards.
JL

**Comment by constantinius** [comment]
Thanks @JannesLathouwers will investigate and fix this

**Comment by constantinius** [comment]
@JannesLathouwers the issue should now be fixed in bot helm-charts and helm-charts-dev
