### ISSUE TITLE
Re-deploying workspaces

### ISSUE THREAD

**Issue by constantinius** [EOEPCA/rm-workspace-api#2]
Currently there is no way to update the configuration of a workspace.

A new route shall be added `POST /workspace/<workspace>/redeploy`

**Comment by rconway** [comment]
The user's persistence should not be lost in the redeploy

**Comment by constantinius** [comment]
Yes, that is true. I will use a `patch` on the Helmrelease. This should preserve everything.

**Comment by rconway** [comment]
Maybe persistence is also at the root of issue #1 - inability to recreate after deletion?

**Comment by constantinius** [comment]
No, I suspect this is due to the bucket not being cleaned up. Not sure how to handle that
