### ISSUE TITLE
OpenAPI Document

### ISSUE THREAD

**Issue by christophreimer** [EOEPCA/rm-workspace-api#20]
@rconway, @Schpidi and @constantinius for documentation purposes would it be possible to publish the latest OpenAPI document of the workspace API you developed? What is the overall status of the API?

**Comment by rconway** [comment]
Hi Christoph,
Here is the openapi.json for the current workspace API.
Richard
[openapi.zip](https://github.com/EOEPCA/rm-workspace-api/files/12463937/openapi.zip)

**Comment by christophreimer** [comment]
thx @rconway
